apiVersion: apps/v1
kind: Deployment
metadata:
  name: medicalrepresentativeschedulerservice-deployment
  labels:
    app: MedicalRepresentativeSchedulerService
spec:
  replicas: 1
  selector:
    matchLabels:
      app: MedicalRepresentativeSchedulerService
  template:
    metadata:
      labels:
        app: MedicalRepresentativeSchedulerService
    spec:
      containers:
      - name: medicalrepresentativeschedulerdockerizeimage
        image: myfirstazurecrcog.azurecr.io/medicalrepresentativeschedulerdockerizeimage:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: webapisvcsecret
---
apiVersion: v1
kind: Service
metadata:
  name: medicalrepresentativeschedulerservicesvc
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: MedicalRepresentativeSchedulerService