apiVersion: apps/v1
kind: Deployment
metadata:
  name: authorizationapiservice-deployment
  labels:
    app: AuthorizationApiService
spec:
  replicas: 1
  selector:
    matchLabels:
      app: AuthorizationApiService
  template:
    metadata:
      labels:
        app: AuthorizationApiService
    spec:
      containers:
      - name: authorizationapidockerizeimage
        image: myfirstazurecrcog.azurecr.io/authorizationapidockerizeimage:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: webapisvcsecret
---
apiVersion: v1
kind: Service
metadata:
  name: authorizationapiservicesvcagain
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: AuthorizationApiService